### PR TITLE
Replace feature by option

### PR DESCRIPTION
**Pull request by gogo2464**
Fixes https://github.com/j-selby/oxidgb/issues/6.

This is not working yet. Let me fix some changes.

### CODE REVIEW

**Comment by gogo2464** [comment]
I have not finish yet. There are still some interesting changes. The broken point is core/src/cpu/mod.rs where the debugger feature macro still has effects. I am going to make another PR to split the mod.rs into 3 files.

**Comment by gogo2464** [comment]
See https://github.com/j-selby/oxidgb/issues/8

**Comment by j-selby** [comment]
As mentioned in Discord, I'm concerned that this just worsens the issue - the ideal solution would be a callback API or traits.

**Comment by gogo2464** [comment]
What do you mean?

**Pull request closed without merging**
